import matplotlib.pyplot as plt

figure,ax = plt.subplots(1,1)

CELL_DEACTIVATION_MIN_STEPS = 350

MAX_OXYGEN_CAPACITY = 100

CAPILLARY_GROWTH_FRACTION = 0.85

# limit on the number of capillaries around the new one
CAPILLARY_GROWTH_DENSITY_LIMIT = 4

CANCER_OXYGEN_CONSUMPTION = 10

CANCER_OXYGEN_VEGF_LIMIT = 30

CANCER_OXYGEN_DUPLICATION_LIMIT = 30

CANCER_DUPLICATION_CHANCE = 0.5

CANCER_DUPLICATION_OXYGEN_COST = 20

CANCER_VEGF_SUPPLY = 40

CANCER_VEGF_CHANCE = 0.05

NORMAL_OXYGEN_CONSUMPTION = 1

CELL_OXYGEN_CONSUMPTION = 1